# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get install texlive-full -y
  - sudo apt-get install haskell-platform -y

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
